/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "Rx.h"
#include "Rx_aliases.h"
#include "Tx.h"
#include "Tx_aliases.h"
#include "uartRx_isr.h"
#include "OutputReg.h"
#include "SDPT_0.h"
#include "SDPT_0_aliases.h"
#include "SPDT_1.h"
#include "SPDT_1_aliases.h"
#include "SP8T_0.h"
#include "SP8T_0_aliases.h"
#include "SP8T_1.h"
#include "SP8T_1_aliases.h"
#include "SP8T_2.h"
#include "SP8T_2_aliases.h"
#include "UART_IntClock.h"
#include "CydwClock_1.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

